/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

import control.Controlador;

/**
 *
 * @author vchin
 */
public class Juego extends javax.swing.JFrame {

    private Controlador elControlador = new Controlador();
    /**
     * Creates new form PantallaPrincipal
     */
    public Juego() {
        initComponents();
        this.elControlador.crear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnJugador = new javax.swing.JButton();
        btnCrearPersonaje = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnConsultarHab = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnCrearArma = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnCrearHab = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnConsultarPer = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnConsultarArmas = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(940, 734));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 734));
        jPanel1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 72)); // NOI18N
        lblTitulo.setText("Implentacion Juego");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(280, 20, 430, 84);

        btnJugador.setBackground(new java.awt.Color(255, 255, 255));
        btnJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personaje.gif"))); // NOI18N
        btnJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugador);
        btnJugador.setBounds(40, 150, 190, 180);

        btnCrearPersonaje.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearPersonaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personaje.jpg"))); // NOI18N
        btnCrearPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPersonajeActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearPersonaje);
        btnCrearPersonaje.setBounds(270, 150, 190, 180);

        jLabel4.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel4.setText("Consultar Armas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 630, 190, 50);

        jLabel5.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel5.setText("Comenzar a Jugar");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(740, 630, 190, 50);

        btnConsultarHab.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/habilidad.gif"))); // NOI18N
        btnConsultarHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarHabActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarHab);
        btnConsultarHab.setBounds(510, 440, 190, 180);

        jLabel10.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel10.setText("Crear Jugador");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 340, 160, 40);

        btnCrearArma.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearArma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arm.png"))); // NOI18N
        btnCrearArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearArmaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearArma);
        btnCrearArma.setBounds(510, 150, 190, 180);

        jLabel18.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel18.setText("Crear Personaje");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(270, 340, 190, 50);

        btnCrearHab.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spell_1.gif"))); // NOI18N
        btnCrearHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearHabActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearHab);
        btnCrearHab.setBounds(730, 150, 190, 180);

        jLabel19.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel19.setText("Crear Armas");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(510, 340, 190, 50);

        btnConsultarPer.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarPer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/kirby.gif"))); // NOI18N
        btnConsultarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPerActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarPer);
        btnConsultarPer.setBounds(40, 440, 190, 180);

        jLabel20.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel20.setText("Crear Habilidades");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(730, 340, 190, 50);

        btnConsultarArmas.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarArmas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arm.gif"))); // NOI18N
        btnConsultarArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarArmasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarArmas);
        btnConsultarArmas.setBounds(270, 440, 200, 180);

        jLabel21.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel21.setText("Consultar Personajes");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(30, 630, 240, 50);

        btnJugar.setBackground(new java.awt.Color(255, 255, 255));
        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fight.gif"))); // NOI18N
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugar);
        btnJugar.setBounds(740, 440, 190, 180);

        jLabel6.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel6.setText("Consultar Habilidades");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(490, 630, 240, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugadorActionPerformed
        CrearJugador pant1 = new CrearJugador(this, true,elControlador);
        pant1.setVisible(true);  
    }//GEN-LAST:event_btnJugadorActionPerformed

    private void btnCrearPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPersonajeActionPerformed
        CrearPersonaje pant1 = new CrearPersonaje(this, true,elControlador);
        pant1.setVisible(true);       
    }//GEN-LAST:event_btnCrearPersonajeActionPerformed

    private void btnCrearArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearArmaActionPerformed
        CrearArma pant1 = new CrearArma(this, true,elControlador);
        pant1.setVisible(true);   
    }//GEN-LAST:event_btnCrearArmaActionPerformed

    private void btnCrearHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearHabActionPerformed
        CrearHabilidad pant1 = new CrearHabilidad(this, true,elControlador);
        pant1.setVisible(true);   
    }//GEN-LAST:event_btnCrearHabActionPerformed

    private void btnConsultarArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarArmasActionPerformed
        ConsultarArmas pant1 = new ConsultarArmas(this, true,elControlador);
        pant1.setVisible(true);   
    }//GEN-LAST:event_btnConsultarArmasActionPerformed

    private void btnConsultarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPerActionPerformed
        ConsultarPersonajes pant1 = new ConsultarPersonajes(this, true,elControlador);
        pant1.setVisible(true);   
    }//GEN-LAST:event_btnConsultarPerActionPerformed

    private void btnConsultarHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarHabActionPerformed
        ConsultarHabilidades pant1 = new ConsultarHabilidades(this, true,elControlador);
        pant1.setVisible(true);   
    }//GEN-LAST:event_btnConsultarHabActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        Jugar pant1 = new Jugar(this, true,elControlador);
        pant1.setVisible(true);   
    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarArmas;
    private javax.swing.JButton btnConsultarHab;
    private javax.swing.JButton btnConsultarPer;
    private javax.swing.JButton btnCrearArma;
    private javax.swing.JButton btnCrearHab;
    private javax.swing.JButton btnCrearPersonaje;
    private javax.swing.JButton btnJugador;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
