/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

/**
 *
 * @author vchin
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCrearCounter = new javax.swing.JButton();
        btnRegistrarClient = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRecepcion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnModificarClient = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnConsultarClient = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnEliminarClient = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        btnReporteClients = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(940, 734));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 734));
        jPanel1.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 72)); // NOI18N
        lblTitulo.setText("Implentacion Juego");
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(280, 20, 430, 84);

        btnCrearCounter.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearCounter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugador.png"))); // NOI18N
        btnCrearCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCounterActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearCounter);
        btnCrearCounter.setBounds(40, 150, 190, 180);

        btnRegistrarClient.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personaje.jpg"))); // NOI18N
        btnRegistrarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClientActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarClient);
        btnRegistrarClient.setBounds(270, 150, 190, 180);

        jLabel4.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel4.setText("Consultar Armas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 630, 190, 50);

        jLabel5.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel5.setText("Consultar Habilidades");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(650, 630, 220, 50);

        btnRecepcion.setBackground(new java.awt.Color(255, 255, 255));
        btnRecepcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/habilidad2.jpg"))); // NOI18N
        btnRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcionActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecepcion);
        btnRecepcion.setBounds(650, 440, 190, 180);

        jLabel10.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel10.setText("Crear Jugador");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 340, 160, 40);

        btnModificarClient.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arm.png"))); // NOI18N
        btnModificarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClientActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarClient);
        btnModificarClient.setBounds(510, 150, 190, 180);

        jLabel18.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel18.setText("Crear Personaje");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(270, 340, 190, 50);

        btnConsultarClient.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/habilidad.jpg"))); // NOI18N
        btnConsultarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClientActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarClient);
        btnConsultarClient.setBounds(730, 150, 190, 180);

        jLabel19.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel19.setText("Crear Armas");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(510, 340, 190, 50);

        btnEliminarClient.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personaje2.jpg"))); // NOI18N
        btnEliminarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClientActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarClient);
        btnEliminarClient.setBounds(140, 440, 190, 180);

        jLabel20.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel20.setText("Crear Habilidades");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(730, 340, 190, 50);

        btnReporteClients.setBackground(new java.awt.Color(255, 255, 255));
        btnReporteClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/arm2.png"))); // NOI18N
        btnReporteClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteClientsActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporteClients);
        btnReporteClients.setBounds(400, 440, 200, 180);

        jLabel21.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 36)); // NOI18N
        jLabel21.setText("Consultar Personajes");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(140, 630, 210, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCounterActionPerformed
        
    }//GEN-LAST:event_btnCrearCounterActionPerformed

    private void btnRegistrarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClientActionPerformed
        
    }//GEN-LAST:event_btnRegistrarClientActionPerformed

    private void btnModificarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClientActionPerformed
        
    }//GEN-LAST:event_btnModificarClientActionPerformed

    private void btnConsultarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClientActionPerformed
        
    }//GEN-LAST:event_btnConsultarClientActionPerformed

    private void btnReporteClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteClientsActionPerformed
        
    }//GEN-LAST:event_btnReporteClientsActionPerformed

    private void btnEliminarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClientActionPerformed
        
    }//GEN-LAST:event_btnEliminarClientActionPerformed

    private void btnRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionActionPerformed
        
    }//GEN-LAST:event_btnRecepcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarClient;
    private javax.swing.JButton btnCrearCounter;
    private javax.swing.JButton btnEliminarClient;
    private javax.swing.JButton btnModificarClient;
    private javax.swing.JButton btnRecepcion;
    private javax.swing.JButton btnRegistrarClient;
    private javax.swing.JButton btnReporteClients;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
